
## org.springframework.boot.autoconfigure.web.ServerProperties
server:
  port: 7080
  session-timeout: 2592000  # 单位: 秒. <= 30 * 24 * 60 * 60


online: false

# dubbo
spring:
    dubbo:
      application:
       name: system-dubbo-provider
      registry:
        address: zookeeper://47.52.198.122:2181
      protocol:
        name: dubbo
        port: 20880
      scan:
        base-packages: com.athen.system.service


# 默认会去找 classpath 下的 logback.xml. 为了达到 profile 的目的故意不用这个文件名
#logging.config: classpath:log-dev.xml

# 数据源配置
druid:
  url: jdbc:mysql://47.52.198.122:3306/athen-priview?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.athen.system.ShowSqlInterceptor
  userName: root
  password: chenying
  filters: stat,wall