
## org.springframework.boot.autoconfigure.web.ServerProperties
server:
  port: 9072
  session-timeout: 2592000  # 单位: 秒. <= 30 * 24 * 60 * 60
  servlet:
    context-path: /config-server

#spring name and  cloud config
spring:
    application:
             name: config-server
    profiles:
      active: mybatis
  #  security:
  #    user:
   #     name: admin
   #     password: chenying521
    freemarker:
      request-context-attribute: rc
      settings:
        template_exception_handler: rethrow
        template_update_delay: 0
        classic_compatible: true
        number_format: 0.######

# 默认会去找 classpath 下的 logback.xml. 为了达到 profile 的目的故意不用这个文件名
#logging.config: classpath:log-dev.xml


# 数据源配置
datasource:
         group:
           master:
             url: jdbc:mysql://47.52.198.122:3306/athen-config-test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&autoReconnect=true&transformedBitIsBoolean=true
             userName: root
             password: chenying
             driver-class-name: com.mysql.cj.jdbc.Driver
         # 连接池配置
         pool:
           connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
           filters: stat,log4j #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
           testWhileIdle: true

logging:
  pattern:
    level: DEBUG
