[#ftl]
[#-- @implicitly included --]
[#-- @ftlroot "../resources/templates" --]
[#-- @ftlvariable name="online" type="java.lang.Boolean" --]
[#-- @ftlvariable name="version" type="java.lang.String" --]
[#-- @ftlvariable name="A" type="com.athen.core.util.A.static" --]
[#-- @ftlvariable name="U" type="com.athen.core.util.U.static" --]
[#-- @ftlvariable name="Money" type="com.athen.core.util.Money.static" --]
[#-- @ftlvariable name="DateUtil" type="com.athen.core.date.DateUtil.static" --]
[#-- @ftlvariable name="Render" type="com.athen.core.util.Render.static" --]
[#-- @ftlvariable name="ImgResolver" type="com.athen.core.util.ImgResolver.static" --]
[#-- @ftlvariable name="domain" type="com.athen.core.util.RenderDomain" --]
[#-- @ftlvariable name="SessionUtil" type="com.athen.system.util.SessionUtil.static" --]
